package view;

import controller.MilitarController;
import controller.Utils;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.EnumPenalidade;
import model.EnumTarefa;
import model.LogAtividade;
import model.Militar;

/**
 * Frame para fazer a Busca de Militar em relação as Tarefas efetuadas com os Botoes Tarefa, Tarefa nao Feita
 Também é utilizado para Deletar e Listar os Militares presentes no ArrayList
 * @author Luiz Ferreira
 * @since 26/08/2017
 */
public class FrameTarefas extends javax.swing.JFrame {
    
    FrameMain parentFrame = null;
    Militar militarAtual = null;
    
    private ArrayList<javax.swing.JCheckBox> checkBoxes = new ArrayList<>();
    private ArrayList<javax.swing.JRadioButton> rbPenalidades = new ArrayList<>();
    
    private void initComponentLists() {
        checkBoxes.add(chkDescascarBatatas);
        checkBoxes.add(chkLimparBanheiro);
        checkBoxes.add(chkLimparCozinha);
        checkBoxes.add(chkCozinharAlmoco);
        checkBoxes.add(chkCozinharJanta);
        checkBoxes.add(chkAlimentarCavalos);
        checkBoxes.add(chkLimparEstabulos);
        checkBoxes.add(chkRecarregar);
        checkBoxes.add(chkTrocarEncanamento);
        checkBoxes.add(chkLevantarBandeira);
        
        rbPenalidades.add(rbAdvertencia);
        rbPenalidades.add(rbImpedimentoDisciplinar);
        rbPenalidades.add(rbRepreensao);
        rbPenalidades.add(rbDetencaoDisciplinar);
        rbPenalidades.add(rbPrisaoDisciplinar);
        rbPenalidades.add(rbLicenciamentoExclusao);
        
        for(int i = 0; i < rbPenalidades.size(); i++)
            rbPenalidades.get(i).setText(EnumPenalidade.values()[i].getNome());
        
        btConfirmar.setEnabled(false);
    }
    
    public FrameTarefas() {
        initComponents();
        initComponentLists();
    }
    
    public FrameTarefas(FrameMain militar){
         initComponents();
         initComponentLists();
         setLocationRelativeTo(null);
         parentFrame = militar;
    }
    //Limpa as Tarefas Do Militar colocando tudo em False.
    private void limparTarefas(Militar solda){
        //todo
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPenalidades = new javax.swing.ButtonGroup();
        buttonGroupExecutouAtividades = new javax.swing.ButtonGroup();
        panelDadosMilitar = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblRg = new javax.swing.JLabel();
        lblNascimento = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblPatente = new javax.swing.JLabel();
        lblPatenteIcon = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        tfIdade = new javax.swing.JTextField();
        ftfCpf = new javax.swing.JFormattedTextField();
        ftfRg = new javax.swing.JFormattedTextField();
        ftfNascimento = new javax.swing.JFormattedTextField();
        cbEstado = new javax.swing.JComboBox<>();
        tfSexo = new javax.swing.JTextField();
        BtBuscarMilitar = new javax.swing.JButton();
        panelTarefas = new javax.swing.JPanel();
        chkDescascarBatatas = new javax.swing.JCheckBox();
        chkLimparBanheiro = new javax.swing.JCheckBox();
        chkLimparCozinha = new javax.swing.JCheckBox();
        chkCozinharAlmoco = new javax.swing.JCheckBox();
        chkCozinharJanta = new javax.swing.JCheckBox();
        chkAlimentarCavalos = new javax.swing.JCheckBox();
        chkLimparEstabulos = new javax.swing.JCheckBox();
        chkRecarregar = new javax.swing.JCheckBox();
        chkTrocarEncanamento = new javax.swing.JCheckBox();
        chkLevantarBandeira = new javax.swing.JCheckBox();
        panelPenalidades = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rbAdvertencia = new javax.swing.JRadioButton();
        rbImpedimentoDisciplinar = new javax.swing.JRadioButton();
        rbRepreensao = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rbDetencaoDisciplinar = new javax.swing.JRadioButton();
        rbPrisaoDisciplinar = new javax.swing.JRadioButton();
        rbLicenciamentoExclusao = new javax.swing.JRadioButton();
        panelAcoes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ftfAtividadeData = new javax.swing.JFormattedTextField();
        rbAtividadeSim = new javax.swing.JRadioButton();
        rbAtividadeNao = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        btVoltar = new javax.swing.JButton();
        btConfirmar = new javax.swing.JButton();
        btLogAtividades = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Tarefas");
        setBackground(new java.awt.Color(164, 199, 158));

        panelDadosMilitar.setBackground(new java.awt.Color(164, 199, 158));
        panelDadosMilitar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Dados do Militar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft JhengHei Light", 1, 13), new java.awt.Color(51, 102, 0))); // NOI18N

        lblCodigo.setText("Código");

        lblNome.setText("Nome");

        lblSexo.setText("Sexo");

        lblCpf.setText("CPF");

        lblRg.setText("RG");

        lblNascimento.setText("Nascimento");

        lblIdade.setText("Idade");

        lblEstado.setText("Estado");

        lblPatente.setText("Patente");

        tfNome.setEnabled(false);
        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        tfIdade.setEnabled(false);

        try {
            ftfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftfRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-*")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftfNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfNascimento.setEnabled(false);

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SP", "RJ", "MG", "ES", "DF" }));
        cbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoActionPerformed(evt);
            }
        });

        tfSexo.setEditable(false);
        tfSexo.setEnabled(false);

        BtBuscarMilitar.setText("Buscar Militar");
        BtBuscarMilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarMilitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDadosMilitarLayout = new javax.swing.GroupLayout(panelDadosMilitar);
        panelDadosMilitar.setLayout(panelDadosMilitarLayout);
        panelDadosMilitarLayout.setHorizontalGroup(
            panelDadosMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosMilitarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDadosMilitarLayout.createSequentialGroup()
                        .addComponent(lblCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfRg, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDadosMilitarLayout.createSequentialGroup()
                        .addComponent(lblPatente)
                        .addGap(18, 18, 18)
                        .addComponent(lblPatenteIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtBuscarMilitar))
                    .addGroup(panelDadosMilitarLayout.createSequentialGroup()
                        .addComponent(lblNascimento)
                        .addGap(18, 18, 18)
                        .addComponent(ftfNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblIdade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(lblSexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfSexo))
                    .addGroup(panelDadosMilitarLayout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNome)))
                .addContainerGap())
        );
        panelDadosMilitarLayout.setVerticalGroup(
            panelDadosMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosMilitarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelDadosMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpf)
                    .addComponent(ftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRg)
                    .addComponent(ftfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstado)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDadosMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDadosMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNascimento)
                    .addComponent(ftfNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdade)
                    .addComponent(tfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSexo)
                    .addComponent(tfSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDadosMilitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDadosMilitarLayout.createSequentialGroup()
                        .addComponent(lblPatente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblPatenteIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDadosMilitarLayout.createSequentialGroup()
                        .addGap(0, 74, Short.MAX_VALUE)
                        .addComponent(BtBuscarMilitar)))
                .addContainerGap())
        );

        panelTarefas.setBackground(new java.awt.Color(164, 199, 158));
        panelTarefas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Quadro de Tarefas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 102, 0))); // NOI18N

        chkDescascarBatatas.setText("Descascar Batatas");
        chkDescascarBatatas.setEnabled(false);

        chkLimparBanheiro.setText("Limpar Banheiro");
        chkLimparBanheiro.setEnabled(false);

        chkLimparCozinha.setText("Limpar Cozinha");
        chkLimparCozinha.setEnabled(false);

        chkCozinharAlmoco.setText("Cozinhar almoço");
        chkCozinharAlmoco.setEnabled(false);

        chkCozinharJanta.setText("Cozinhar Janta");
        chkCozinharJanta.setEnabled(false);

        chkAlimentarCavalos.setText("Alimentar Cavalos");
        chkAlimentarCavalos.setEnabled(false);

        chkLimparEstabulos.setText("Limpar Estabulos");
        chkLimparEstabulos.setEnabled(false);

        chkRecarregar.setText("Recarregar Armamento");
        chkRecarregar.setEnabled(false);

        chkTrocarEncanamento.setText("Trocar encanamento");
        chkTrocarEncanamento.setEnabled(false);

        chkLevantarBandeira.setText("Levantar Bandeira");
        chkLevantarBandeira.setEnabled(false);

        javax.swing.GroupLayout panelTarefasLayout = new javax.swing.GroupLayout(panelTarefas);
        panelTarefas.setLayout(panelTarefasLayout);
        panelTarefasLayout.setHorizontalGroup(
            panelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarefasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkDescascarBatatas)
                    .addComponent(chkLimparBanheiro)
                    .addComponent(chkLimparCozinha)
                    .addComponent(chkCozinharAlmoco))
                .addGap(59, 59, 59)
                .addGroup(panelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTarefasLayout.createSequentialGroup()
                        .addGroup(panelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkCozinharJanta)
                            .addComponent(chkAlimentarCavalos)
                            .addComponent(chkLimparEstabulos))
                        .addGap(43, 43, 43)
                        .addGroup(panelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkTrocarEncanamento)
                            .addComponent(chkLevantarBandeira)))
                    .addComponent(chkRecarregar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTarefasLayout.setVerticalGroup(
            panelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarefasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkDescascarBatatas)
                    .addComponent(chkCozinharJanta)
                    .addComponent(chkTrocarEncanamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkLimparBanheiro)
                    .addComponent(chkAlimentarCavalos)
                    .addComponent(chkLevantarBandeira))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkLimparCozinha)
                    .addComponent(chkLimparEstabulos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCozinharAlmoco)
                    .addComponent(chkRecarregar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPenalidades.setBackground(new java.awt.Color(164, 199, 158));
        panelPenalidades.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Penalidades", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 51, 51))); // NOI18N

        jLabel8.setText("Grau 1");

        jLabel9.setText("Grau 2");

        jLabel10.setText("Grau 3");

        buttonGroupPenalidades.add(rbAdvertencia);
        rbAdvertencia.setText("nome_alterado_dinamicamente");
        rbAdvertencia.setEnabled(false);

        buttonGroupPenalidades.add(rbImpedimentoDisciplinar);
        rbImpedimentoDisciplinar.setText("nome_alterado_dinamicamente");
        rbImpedimentoDisciplinar.setEnabled(false);

        buttonGroupPenalidades.add(rbRepreensao);
        rbRepreensao.setText("nome_alterado_dinamicamente");
        rbRepreensao.setEnabled(false);
        rbRepreensao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRepreensaoActionPerformed(evt);
            }
        });

        jLabel3.setText("Grau 4");

        jLabel4.setText("Grau 5");

        jLabel5.setText("Grau 6");

        buttonGroupPenalidades.add(rbDetencaoDisciplinar);
        rbDetencaoDisciplinar.setText("nome_alterado_dinamicamente");
        rbDetencaoDisciplinar.setEnabled(false);

        buttonGroupPenalidades.add(rbPrisaoDisciplinar);
        rbPrisaoDisciplinar.setText("nome_alterado_dinamicamente");
        rbPrisaoDisciplinar.setEnabled(false);

        buttonGroupPenalidades.add(rbLicenciamentoExclusao);
        rbLicenciamentoExclusao.setText("nome_alterado_dinamicamente");
        rbLicenciamentoExclusao.setEnabled(false);
        rbLicenciamentoExclusao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLicenciamentoExclusaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPenalidadesLayout = new javax.swing.GroupLayout(panelPenalidades);
        panelPenalidades.setLayout(panelPenalidadesLayout);
        panelPenalidadesLayout.setHorizontalGroup(
            panelPenalidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPenalidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPenalidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPenalidadesLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbAdvertencia))
                    .addGroup(panelPenalidadesLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbImpedimentoDisciplinar))
                    .addGroup(panelPenalidadesLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbRepreensao)))
                .addGap(19, 19, 19)
                .addGroup(panelPenalidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPenalidadesLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbPrisaoDisciplinar))
                    .addGroup(panelPenalidadesLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbDetencaoDisciplinar))
                    .addGroup(panelPenalidadesLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbLicenciamentoExclusao)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPenalidadesLayout.setVerticalGroup(
            panelPenalidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPenalidadesLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panelPenalidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbAdvertencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbDetencaoDisciplinar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(panelPenalidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbImpedimentoDisciplinar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbPrisaoDisciplinar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(panelPenalidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbRepreensao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbLicenciamentoExclusao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelAcoes.setBackground(new java.awt.Color(164, 199, 158));
        panelAcoes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Controle de Execução", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 102, 0))); // NOI18N

        jLabel1.setText("Data de execução:");

        try {
            ftfAtividadeData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfAtividadeData.setEnabled(false);

        buttonGroupExecutouAtividades.add(rbAtividadeSim);
        rbAtividadeSim.setText("Sim");
        rbAtividadeSim.setEnabled(false);

        buttonGroupExecutouAtividades.add(rbAtividadeNao);
        rbAtividadeNao.setText("Não");
        rbAtividadeNao.setEnabled(false);
        rbAtividadeNao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbAtividadeNaoItemStateChanged(evt);
            }
        });

        jLabel2.setText("Cumpriu todas as atividades do dia?");

        javax.swing.GroupLayout panelAcoesLayout = new javax.swing.GroupLayout(panelAcoes);
        panelAcoes.setLayout(panelAcoesLayout);
        panelAcoesLayout.setHorizontalGroup(
            panelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAcoesLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftfAtividadeData, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbAtividadeSim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(rbAtividadeNao)
                .addContainerGap())
        );
        panelAcoesLayout.setVerticalGroup(
            panelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAcoesLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(panelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ftfAtividadeData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbAtividadeSim)
                    .addComponent(rbAtividadeNao)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btConfirmar.setBackground(new java.awt.Color(153, 153, 153));
        btConfirmar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btConfirmar.setForeground(new java.awt.Color(51, 102, 0));
        btConfirmar.setText("Confirmar");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });

        btLogAtividades.setText("Log de atividades");
        btLogAtividades.setEnabled(false);
        btLogAtividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogAtividadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btLogAtividades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(panelDadosMilitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelAcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelPenalidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDadosMilitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(panelTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPenalidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLogAtividades)
                    .addComponent(btConfirmar)
                    .addComponent(btVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDadosMilitar.getAccessibleContext().setAccessibleDescription("");
        panelPenalidades.getAccessibleContext().setAccessibleDescription("");
        panelAcoes.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //Botão Tarefa Feita faz com que a Tarefa de um Certo Militar seja Coloca tudo em False que significa "FEITO"=False  e Não Feito= "true"
    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        if(militarAtual != null) {
            String dataStr = ftfAtividadeData.getText();
            if(dataStr.trim().equals("")) {
                JOptionPane.showMessageDialog(null, "A data de confirmação da atividade deve ser preenchida.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }
            Date data = Utils.stringToDate(dataStr);
            boolean executouAtividade = rbAtividadeSim.isSelected();
            MilitarController.logExecucaoAtividade(militarAtual,executouAtividade,executouAtividade ? 0 : militarAtual.getGrauPenalidade()+1,data);
            
            ftfAtividadeData.setText("");
            buttonGroupExecutouAtividades.clearSelection();
            if(militarAtual.getGrauPenalidade() > 0) {
                rbPenalidades.get(militarAtual.getGrauPenalidade()-1).setSelected(rootPaneCheckingEnabled);
            }
            else {
                buttonGroupPenalidades.clearSelection();
            }
        }
    }//GEN-LAST:event_btConfirmarActionPerformed

    //limpa os campos
    private void limparCampos() {
        tfNome.setText("");
        ftfCpf.setText("");
        ftfRg.setText("");
        ftfNascimento.setText("");
        tfIdade.setText("");
        cbEstado.setSelectedIndex(-1);
        tfSexo.setText("");
        for(javax.swing.JCheckBox c : checkBoxes) {
            c.setSelected(false);
        }
        buttonGroupPenalidades.clearSelection();
        btConfirmar.setEnabled(false);
        btLogAtividades.setEnabled(false);
    }
    
    private void setCamposFromMilitar(Militar militar) {
        tfCodigo.setText("" + militar.getCodigo());
        tfNome.setText(militar.getNome());
        ftfCpf.setText(militar.getCpf());
        ftfRg.setText(militar.getRg());
        cbEstado.setSelectedItem(militar.getEstado());
        tfSexo.setText(militar.getSexo() == 'M' ? "Masculino" : "Feminino");
        ftfNascimento.setText(Utils.dateToString(militar.getNascimento()));
        ImageIcon patenteImagem = new ImageIcon(getClass().getResource("/images/" + militar.getPatente().getImagem()));
        int size = patenteImagem.getIconHeight();
        //lblPatenteIcon.setSize(patenteImagem.getIconWidth(),patenteImagem.getIconHeight());
        lblPatenteIcon.setIcon(patenteImagem);
        lblPatenteIcon.setToolTipText(militar.getPatente().getNome());
        String nascimento = ftfNascimento.getText();
        int idade = Utils.getAgeInYears(Utils.stringToDate(nascimento));
        tfIdade.setText(""+idade);
        for(int i = 0; i < checkBoxes.size(); i++) {
            checkBoxes.get(i).setSelected(militar.fazAtividade(EnumTarefa.values()[i]));
        }
        if(militar.getGrauPenalidade() > 0) {
            rbPenalidades.get(militar.getGrauPenalidade()-1).setSelected(rootPaneCheckingEnabled);
        }
        else {
            buttonGroupPenalidades.clearSelection();
        }
    }
    //Botão Buscar ao apertar ele Buscar o Militar que você Deseja Encontrar através do nome.
    private void BtBuscarMilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarMilitarActionPerformed
        String codigoStr = tfCodigo.getText();
        String cpf = ftfCpf.getText();
        String rg = ftfRg.getText();
        String estado = (String)cbEstado.getSelectedItem();

        int tipoBusca = 0;
        if(codigoStr.trim().equals("")) {
            if(cpf.trim().replaceAll("[-./]","").equals("")) {
                tipoBusca = 2;
            }
            else
                tipoBusca = 1;
        }
        
        Militar militar;
        if(tipoBusca == 0) {
            int codigo = Utils.stringToInt(codigoStr);
            militar = MilitarController.buscarMilitar(codigo);
        }
        else if(tipoBusca == 1)
            militar = MilitarController.buscarMilitarCPF(cpf);
        else
            militar = MilitarController.buscarMilitarRG(rg,estado);

        if(militar != null) {
            setCamposFromMilitar(militar);
            ftfAtividadeData.setEnabled(true);
            rbAtividadeSim.setEnabled(true);
            rbAtividadeNao.setEnabled(true);
            btConfirmar.setEnabled(true);
            btLogAtividades.setEnabled(true);
            militarAtual = militar;
        }
        else {
            limparCampos();
            militarAtual = null;
        }
    }//GEN-LAST:event_BtBuscarMilitarActionPerformed
     
    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed
    
      
    private void cbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEstadoActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void rbAtividadeNaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbAtividadeNaoItemStateChanged
        if(militarAtual == null)
            return;
        
        int grauPenalidade = militarAtual.getGrauPenalidade();
        if(evt.getStateChange() == ItemEvent.SELECTED) {
            grauPenalidade += 1;
            if(grauPenalidade > EnumPenalidade.getCount())
                grauPenalidade = EnumPenalidade.getCount();
        }

        if(grauPenalidade == 0) {
            buttonGroupPenalidades.clearSelection();
        }
        else {
            rbPenalidades.get(grauPenalidade-1).setSelected(true);
        }
    }//GEN-LAST:event_rbAtividadeNaoItemStateChanged

    private void btLogAtividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogAtividadesActionPerformed
        if(militarAtual == null)
            return;

        List<LogAtividade> logAtividades = MilitarController.listarAtividadesExecutadas(militarAtual);
        FrameListagemLogAtividades frameLogAtividade = new FrameListagemLogAtividades(militarAtual,logAtividades);
        frameLogAtividade.setVisible(true);
    }//GEN-LAST:event_btLogAtividadesActionPerformed

    private void rbLicenciamentoExclusaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLicenciamentoExclusaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLicenciamentoExclusaoActionPerformed

    private void rbRepreensaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRepreensaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbRepreensaoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBuscarMilitar;
    private javax.swing.JButton btConfirmar;
    private javax.swing.JButton btLogAtividades;
    private javax.swing.JButton btVoltar;
    private javax.swing.ButtonGroup buttonGroupExecutouAtividades;
    private javax.swing.ButtonGroup buttonGroupPenalidades;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JCheckBox chkAlimentarCavalos;
    private javax.swing.JCheckBox chkCozinharAlmoco;
    private javax.swing.JCheckBox chkCozinharJanta;
    private javax.swing.JCheckBox chkDescascarBatatas;
    private javax.swing.JCheckBox chkLevantarBandeira;
    private javax.swing.JCheckBox chkLimparBanheiro;
    private javax.swing.JCheckBox chkLimparCozinha;
    private javax.swing.JCheckBox chkLimparEstabulos;
    private javax.swing.JCheckBox chkRecarregar;
    private javax.swing.JCheckBox chkTrocarEncanamento;
    private javax.swing.JFormattedTextField ftfAtividadeData;
    private javax.swing.JFormattedTextField ftfCpf;
    private javax.swing.JFormattedTextField ftfNascimento;
    private javax.swing.JFormattedTextField ftfRg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPatente;
    private javax.swing.JLabel lblPatenteIcon;
    private javax.swing.JLabel lblRg;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JPanel panelAcoes;
    private javax.swing.JPanel panelDadosMilitar;
    private javax.swing.JPanel panelPenalidades;
    private javax.swing.JPanel panelTarefas;
    private javax.swing.JRadioButton rbAdvertencia;
    private javax.swing.JRadioButton rbAtividadeNao;
    private javax.swing.JRadioButton rbAtividadeSim;
    private javax.swing.JRadioButton rbDetencaoDisciplinar;
    private javax.swing.JRadioButton rbImpedimentoDisciplinar;
    private javax.swing.JRadioButton rbLicenciamentoExclusao;
    private javax.swing.JRadioButton rbPrisaoDisciplinar;
    private javax.swing.JRadioButton rbRepreensao;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfIdade;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfSexo;
    // End of variables declaration//GEN-END:variables
}
