package view;


import model.Militar;
import java.util.ArrayList;


/**
 * FrameMenu usado para a escolha Entre Cadastrar e Buscar Militar, é também onde fica a ArrayList Para manter sempre Aberto.
 * @author Luiz Ferreira
 * @since 26/08/2017
 */
public class FrameMenu extends javax.swing.JFrame {
    
    ArrayList <Militar> sold = new ArrayList();
    String soldado = new String();
    int codigoGlobal = 0;
    public FrameMenu() {
        initComponents();
        
        InserirSoldadoArray();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbExercitoLogo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmMilitar = new javax.swing.JMenu();
        jmCadastrar = new javax.swing.JMenuItem();
        jmBuscar = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(164, 199, 158));
        jPanel1.setToolTipText("");

        lbExercitoLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbExercitoLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exercito_Brasileiro_Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(lbExercitoLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(170, 170, 170))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbExercitoLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        jmMilitar.setBackground(new java.awt.Color(164, 199, 158));
        jmMilitar.setText("Militar");

        jmCadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmCadastrar.setBackground(new java.awt.Color(164, 199, 158));
        jmCadastrar.setText("Cadastrar");
        jmCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastrarActionPerformed(evt);
            }
        });
        jmMilitar.add(jmCadastrar);

        jmBuscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmBuscar.setBackground(new java.awt.Color(164, 199, 158));
        jmBuscar.setText("Buscar");
        jmBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBuscarActionPerformed(evt);
            }
        });
        jmMilitar.add(jmBuscar);

        jmSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmSair.setText("Sair");
        jmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSairActionPerformed(evt);
            }
        });
        jmMilitar.add(jmSair);

        jMenuBar1.add(jmMilitar);

        jMenu2.setText("Sobre");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //passo o FrameCadastro como this para se referir ao conteudo do Frame Menu.
    private void jmCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastrarActionPerformed
        FrameCadastro framesoldado = new FrameCadastro(this);
        framesoldado.setVisible(true);
    }//GEN-LAST:event_jmCadastrarActionPerformed
   
    private void jmBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBuscarActionPerformed
       FrameBuscar framebuscar = new FrameBuscar(this);
       framebuscar.setVisible(true);
    }//GEN-LAST:event_jmBuscarActionPerformed

    private void jmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSairActionPerformed
        dispose();
        
    }//GEN-LAST:event_jmSairActionPerformed
    
    private void InserirSoldadoArray(){
        
        Militar sol = new Militar(123456, "Joao", "12345678912", "360698207", "DF", "Masculino", "29/06/1997", "qualquer coisa", 12 , false, true, true, false, true, false, true, false, true, false, null ,"Major" , 0 );
        
        Militar sol2 = new Militar(123457, "Lucas", "19999998643", "650394800", "BH", "Feminino", "07/09/1900", "qualquer coisa", 67 , true, true, true, true, true, true, true, true, true, true, null ,"Soldado" , 0 );
        
        Militar sol3 = new Militar(123458, "Pedro", "18232768877", "154987611", "SP", "Masculino", "07/09/1967", "qualquer coisa", 67 , true, true, false, true, true, false, true, true, false, true, null ,"Tenente" , 0 );
        
        this.sold.add(sol);
        this.sold.add(sol2);
        this.sold.add(sol3);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMenu().setVisible(true);
            }
        });
    }
    //Salva o soldado
    public void salvarSoldado(Militar soldado){
        sold.add(soldado);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jmBuscar;
    private javax.swing.JMenuItem jmCadastrar;
    private javax.swing.JMenu jmMilitar;
    private javax.swing.JMenuItem jmSair;
    private javax.swing.JLabel lbExercitoLogo;
    // End of variables declaration//GEN-END:variables

   
}
