package view;


import model.Militar;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * @author Luiz Ferreira
 * @since 26/08/2017
 */

public class Tarefas_Militares extends javax.swing.JFrame {
    
    Militar militar = new Militar();
    ArrayList <Militar> milit = new ArrayList();
    public String texto="";
   
    public Tarefas_Militares() {
        initComponents();
    }
    //Deixei como publico pra ve se vai funcionar
private void insererClienteArray(Militar militar) {
        milit.add(militar);
    }
private Militar buscarMilitarNome(String nome){
        Militar milit = null;
        for(int i=0;i<this.milit.size();i++){
            if(nome.equals(this.milit.get(i).getNome())){
                System.out.println("Militar: "+this.milit.get(i).getNome());
                milit = this.milit.get(i);
            }
        }
        if(milit==null){
                JOptionPane.showMessageDialog(null,"Militar não encontrado.");
        }
        return milit;
    }
//deixei como publico mas era private
 private void listarTodosClientesArray(){
        
        for(int i=0;i<milit.size(); i++){
            
            System.out.println("Nome: " + milit.get(i).getNome());
            System.out.println("codigo: "+milit.get(i).getCodigo()+"\n");            
            System.out.println("Alimentar"+milit.get(i).isAlimentarCavalos());
            System.out.println("CozinharARMOCO"+milit.get(i).isCozinharArmoco());
            System.out.println("COzinharJANTA"+milit.get(i).isCozinharJanta());
            System.out.println("DESCANCAR"+milit.get(i).isDescascar());
            System.out.println("BANDEIRA"+milit.get(i).isLevantarBandeira());
            System.out.println("LIMPARCOZINHA"+milit.get(i).isLimparCozinha());
            System.out.println("LimparEstabulos"+milit.get(i).isLimparEstabulos());
            System.out.println("RECARREGAR"+milit.get(i).isRecarregarArmamento());
            System.out.println("ENCANAMENTO"+milit.get(i).isTrocarEncanamento());
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        JpDadosSoldado = new javax.swing.JPanel();
        LbCodigo = new javax.swing.JLabel();
        LbNome = new javax.swing.JLabel();
        LbSexo = new javax.swing.JLabel();
        LbCpf = new javax.swing.JLabel();
        LbRg = new javax.swing.JLabel();
        LbNascimento = new javax.swing.JLabel();
        LbIdade = new javax.swing.JLabel();
        LbEstado = new javax.swing.JLabel();
        ftfCodigo = new javax.swing.JFormattedTextField();
        tfNome = new javax.swing.JTextField();
        ftfCpf = new javax.swing.JFormattedTextField();
        ftfRg = new javax.swing.JFormattedTextField();
        ftfNascimento = new javax.swing.JFormattedTextField();
        ftfIdade = new javax.swing.JFormattedTextField();
        rbMasculino = new javax.swing.JRadioButton();
        rbFeminino = new javax.swing.JRadioButton();
        cbEstado = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        rbComando = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        rbMarechal = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbCoronel = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rbMajor = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rbCapitao = new javax.swing.JRadioButton();
        rbTenente = new javax.swing.JRadioButton();
        rbSoldado = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        chkDescascarBatatas = new javax.swing.JCheckBox();
        chkLimparBanheiro = new javax.swing.JCheckBox();
        chkLimparCozinha = new javax.swing.JCheckBox();
        chkCozinharAlmoco = new javax.swing.JCheckBox();
        chkCozinharJanta = new javax.swing.JCheckBox();
        chkAlimentarCavalos = new javax.swing.JCheckBox();
        chkLimparEstabulos = new javax.swing.JCheckBox();
        chkRecarregar = new javax.swing.JCheckBox();
        chkTrocarEncanamento = new javax.swing.JCheckBox();
        chkLevantarBandeira = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jbTarefaFeita = new javax.swing.JButton();
        jbCadastrarTarefa = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btDeletarSoldado = new javax.swing.JButton();
        btListar = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        BtBuscarSoldado = new javax.swing.JButton();
        btCadastrarSoldado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JpDadosSoldado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Dados do Soldado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft JhengHei Light", 1, 13), new java.awt.Color(51, 102, 0))); // NOI18N

        LbCodigo.setText("Código :");

        LbNome.setText("Nome :");

        LbSexo.setText("Sexo :");

        LbCpf.setText("CPF :");

        LbRg.setText("RG :");

        LbNascimento.setText("Nascimento :");

        LbIdade.setText("Idade :");

        LbEstado.setText("Estado :");

        try {
            ftfCodigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfCodigoActionPerformed(evt);
            }
        });

        try {
            ftfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftfRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftfNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftfIdade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        buttonGroup2.add(rbMasculino);
        rbMasculino.setText("Masculino");
        rbMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMasculinoActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbFeminino);
        rbFeminino.setText("Feminino");

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "SP", "BH", "DF", "RJ" }));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon_rank_Major---.png"))); // NOI18N

        buttonGroup1.add(rbComando);
        rbComando.setText("Comandante");
        rbComando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbComandoActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon_rank_Corporal.png"))); // NOI18N

        buttonGroup1.add(rbMarechal);
        rbMarechal.setText("Marechal");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon_rank_God_of_War.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon_rank_World_Class_Force-.png"))); // NOI18N

        buttonGroup1.add(rbCoronel);
        rbCoronel.setText("Coronel");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download.jpg"))); // NOI18N

        buttonGroup1.add(rbMajor);
        rbMajor.setText("Major");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon_rank_Private.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon_rank_General-.png"))); // NOI18N

        buttonGroup1.add(rbCapitao);
        rbCapitao.setText("Capitão");

        buttonGroup1.add(rbTenente);
        rbTenente.setText("Tenente");

        buttonGroup1.add(rbSoldado);
        rbSoldado.setText("Soldado");

        javax.swing.GroupLayout JpDadosSoldadoLayout = new javax.swing.GroupLayout(JpDadosSoldado);
        JpDadosSoldado.setLayout(JpDadosSoldadoLayout);
        JpDadosSoldadoLayout.setHorizontalGroup(
            JpDadosSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpDadosSoldadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpDadosSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpDadosSoldadoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbCapitao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbTenente)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbSoldado))
                    .addGroup(JpDadosSoldadoLayout.createSequentialGroup()
                        .addGroup(JpDadosSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(JpDadosSoldadoLayout.createSequentialGroup()
                                .addComponent(LbNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JpDadosSoldadoLayout.createSequentialGroup()
                                .addComponent(LbCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JpDadosSoldadoLayout.createSequentialGroup()
                                .addComponent(LbSexo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbMasculino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbFeminino, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(JpDadosSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpDadosSoldadoLayout.createSequentialGroup()
                                .addGroup(JpDadosSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(JpDadosSoldadoLayout.createSequentialGroup()
                                        .addComponent(LbCpf)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ftfCpf))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpDadosSoldadoLayout.createSequentialGroup()
                                        .addComponent(LbRg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ftfRg, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(JpDadosSoldadoLayout.createSequentialGroup()
                                        .addComponent(LbNascimento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ftfNascimento)))
                                .addGap(57, 57, 57)
                                .addGroup(JpDadosSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JpDadosSoldadoLayout.createSequentialGroup()
                                        .addComponent(LbIdade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ftfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(JpDadosSoldadoLayout.createSequentialGroup()
                                        .addComponent(LbEstado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(JpDadosSoldadoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbCoronel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbMajor))))
                    .addGroup(JpDadosSoldadoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbComando)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbMarechal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JpDadosSoldadoLayout.setVerticalGroup(
            JpDadosSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpDadosSoldadoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(JpDadosSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JpDadosSoldadoLayout.createSequentialGroup()
                        .addGroup(JpDadosSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbCodigo)
                            .addComponent(LbCpf)
                            .addComponent(LbIdade)
                            .addComponent(ftfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JpDadosSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbNome)
                            .addComponent(LbRg)
                            .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbEstado)
                            .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JpDadosSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbSexo)
                            .addComponent(LbNascimento)
                            .addComponent(ftfNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbMasculino)
                            .addComponent(rbFeminino))
                        .addGroup(JpDadosSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpDadosSoldadoLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(rbComando))
                            .addGroup(JpDadosSoldadoLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(JpDadosSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JpDadosSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(JpDadosSoldadoLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(rbMarechal))
                            .addGroup(JpDadosSoldadoLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(JpDadosSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbCoronel)
                                    .addComponent(rbMajor))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JpDadosSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(JpDadosSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(rbTenente)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbSoldado)))
                    .addComponent(rbCapitao))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Quadro de Tarefas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        chkDescascarBatatas.setText("Descascar Batatas");
        chkDescascarBatatas.setEnabled(false);

        chkLimparBanheiro.setText("Limpar Banheiro");
        chkLimparBanheiro.setEnabled(false);

        chkLimparCozinha.setText("Limpar Cozinha");
        chkLimparCozinha.setEnabled(false);

        chkCozinharAlmoco.setText("Cozinhar almoço");
        chkCozinharAlmoco.setEnabled(false);

        chkCozinharJanta.setText("Cozinhar Janta");
        chkCozinharJanta.setEnabled(false);

        chkAlimentarCavalos.setText("Alimentar Cavalos");
        chkAlimentarCavalos.setEnabled(false);

        chkLimparEstabulos.setText("Limpar Estabulos");
        chkLimparEstabulos.setEnabled(false);

        chkRecarregar.setText("Recarregar Armamento");
        chkRecarregar.setEnabled(false);

        chkTrocarEncanamento.setText("Trocar encanamento");
        chkTrocarEncanamento.setEnabled(false);

        chkLevantarBandeira.setText("Levantar Bandeira");
        chkLevantarBandeira.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkDescascarBatatas)
                    .addComponent(chkLimparBanheiro)
                    .addComponent(chkLimparCozinha)
                    .addComponent(chkCozinharAlmoco))
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkCozinharJanta)
                            .addComponent(chkAlimentarCavalos)
                            .addComponent(chkLimparEstabulos))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkTrocarEncanamento)
                            .addComponent(chkLevantarBandeira)))
                    .addComponent(chkRecarregar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkDescascarBatatas)
                    .addComponent(chkCozinharJanta)
                    .addComponent(chkTrocarEncanamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkLimparBanheiro)
                    .addComponent(chkAlimentarCavalos)
                    .addComponent(chkLevantarBandeira))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkLimparCozinha)
                    .addComponent(chkLimparEstabulos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCozinharAlmoco)
                    .addComponent(chkRecarregar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Penalidades", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel8.setText("Grau 1");

        jLabel9.setText("Grau 2");

        jLabel10.setText("Grau 3");

        jRadioButton1.setText("700 Flexoes");
        jRadioButton1.setEnabled(false);

        jRadioButton2.setText("2 dias sem almoço");
        jRadioButton2.setEnabled(false);

        jRadioButton3.setText("Multa");
        jRadioButton3.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton3)))
                        .addGap(0, 130, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jRadioButton3))
                .addGap(0, 46, Short.MAX_VALUE))
        );

        jbTarefaFeita.setBackground(new java.awt.Color(153, 153, 153));
        jbTarefaFeita.setForeground(new java.awt.Color(51, 255, 0));
        jbTarefaFeita.setText("Tarefa Feita");
        jbTarefaFeita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTarefaFeitaActionPerformed(evt);
            }
        });

        jbCadastrarTarefa.setText("Cadastrar Tarefa");
        jbCadastrarTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarTarefaActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("Tarefa não Feita");

        btDeletarSoldado.setText("Deletar");

        btListar.setText("Listar Soldado");
        btListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbCadastrarTarefa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbTarefaFeita, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btListar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btDeletarSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbTarefaFeita)
                    .addComponent(jbCadastrarTarefa)
                    .addComponent(btDeletarSoldado)
                    .addComponent(jButton3)
                    .addComponent(btListar))
                .addContainerGap())
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtBuscarSoldado.setText("Buscar Soldado");
        BtBuscarSoldado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarSoldadoActionPerformed(evt);
            }
        });

        btCadastrarSoldado.setText("Cadastrar Soldado");
        btCadastrarSoldado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarSoldadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(BtBuscarSoldado)
                .addGap(51, 51, 51)
                .addComponent(btCadastrarSoldado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtBuscarSoldado)
                    .addComponent(btCadastrarSoldado))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 395, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JpDadosSoldado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JpDadosSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JpDadosSoldado.getAccessibleContext().setAccessibleName("Dados do Militar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ftfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfCodigoActionPerformed

    private void btCadastrarSoldadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarSoldadoActionPerformed
        militar= new Militar();
        militar.setCodigo(Integer.parseInt(ftfCodigo.getText()));
        militar.setNome(tfNome.getText());
        militar.setCpf(ftfCpf.getText());
        militar.setRg(ftfRg.getText());
        militar.setEstado((String) cbEstado.getSelectedItem());
        militar.setSexo(rbMasculino.isSelected()?"Masculino":"Feminino");
        militar.setNascimento(ftfNascimento.getText());
       
        if(rbComando.isSelected()){
            militar.setPatente("Comandante");
            chkDescascarBatatas.setEnabled(false);
            chkLimparBanheiro.setEnabled(false);
            chkLimparCozinha.setEnabled(true);
            chkLimparEstabulos.setEnabled(false);
            chkRecarregar.setEnabled(true);
            chkAlimentarCavalos.setEnabled(true);
            chkCozinharAlmoco.setEnabled(false);
            chkCozinharJanta.setEnabled(false);
            chkTrocarEncanamento.setEnabled(false);
            chkLevantarBandeira.setEnabled(true);
           
            
       }else if(rbMarechal.isSelected()){
            militar.setPatente("Marechal");
            chkDescascarBatatas.setEnabled(false);
            chkLimparBanheiro.setEnabled(false);
            chkLimparCozinha.setEnabled(false);
            chkLimparEstabulos.setEnabled(true);
            chkRecarregar.setEnabled(true);
            chkAlimentarCavalos.setEnabled(false);
            chkCozinharAlmoco.setEnabled(true);
            chkCozinharJanta.setEnabled(true);
            chkTrocarEncanamento.setEnabled(false);
            chkLevantarBandeira.setEnabled(true);
            
           
        }
        else if(rbCoronel.isSelected()){
             militar.setPatente("Coronel");
            chkDescascarBatatas.setEnabled(true);
            chkLimparBanheiro.setEnabled(false);
            chkLimparCozinha.setEnabled(true);
            chkLimparEstabulos.setEnabled(true);
            chkRecarregar.setEnabled(true);
            chkAlimentarCavalos.setEnabled(true);
            chkCozinharAlmoco.setEnabled(true);
            chkCozinharJanta.setEnabled(true);
            chkTrocarEncanamento.setEnabled(true);
            chkLevantarBandeira.setEnabled(true);
            
            
        }
        else if(rbMajor.isSelected()){
            militar.setPatente("Major");
            chkDescascarBatatas.setEnabled(true);
            chkLimparBanheiro.setEnabled(true);
            chkLimparCozinha.setEnabled(true);
            chkLimparEstabulos.setEnabled(false);
            chkRecarregar.setEnabled(true);
            chkAlimentarCavalos.setEnabled(true);
            chkCozinharAlmoco.setEnabled(true);
            chkCozinharJanta.setEnabled(true);
            chkTrocarEncanamento.setEnabled(false);
            chkLevantarBandeira.setEnabled(false);
            
            
        }
        else if(rbCapitao.isSelected()){
            militar.setPatente("Marechal");
            chkDescascarBatatas.setEnabled(true);
            chkLimparBanheiro.setEnabled(false);
            chkLimparCozinha.setEnabled(true);
            chkLimparEstabulos.setEnabled(true);
            chkRecarregar.setEnabled(true);
            chkAlimentarCavalos.setEnabled(true);
            chkCozinharAlmoco.setEnabled(true);
            chkCozinharJanta.setEnabled(true);
            chkTrocarEncanamento.setEnabled(false);
            chkLevantarBandeira.setEnabled(true);
            
            
        }
        else if(rbTenente.isSelected()){
            militar.setPatente("Tenente");
            chkDescascarBatatas.setEnabled(true);
            chkLimparBanheiro.setEnabled(false);
            chkLimparCozinha.setEnabled(true);
            chkLimparEstabulos.setEnabled(true);
            chkRecarregar.setEnabled(true);
            chkAlimentarCavalos.setEnabled(true);
            chkCozinharAlmoco.setEnabled(true);
            chkCozinharJanta.setEnabled(true);
            chkTrocarEncanamento.setEnabled(false);
            chkLevantarBandeira.setEnabled(true);
            
        }
        else if(rbSoldado.isSelected()){
            militar.setPatente("Soldado");
            chkDescascarBatatas.setEnabled(true);
            chkLimparBanheiro.setEnabled(true);
            chkLimparCozinha.setEnabled(true);
            chkLimparEstabulos.setEnabled(true);
            chkRecarregar.setEnabled(true);
            chkAlimentarCavalos.setEnabled(true);
            chkCozinharAlmoco.setEnabled(true);
            chkCozinharJanta.setEnabled(true);
            chkTrocarEncanamento.setEnabled(true);
            chkLevantarBandeira.setEnabled(true);
            
        }
        militar.setIdade(Integer.parseInt(ftfIdade.getText()));
        
        rbSoldado.setEnabled(false);
        rbTenente.setEnabled(false);
        rbCapitao.setEnabled(false);
        rbMajor.setEnabled(false);
        rbCoronel.setEnabled(false);
        rbMarechal.setEnabled(false);
        insererClienteArray(militar);
        
        
        JOptionPane.showMessageDialog(null,"Dados do soldado salvos");
            
    }//GEN-LAST:event_btCadastrarSoldadoActionPerformed
 
    private void BtBuscarSoldadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarSoldadoActionPerformed
        Militar soldier;
        soldier = buscarMilitarNome(tfNome.getText());
        
        ftfCodigo.setText(String.valueOf(militar.getCodigo()));
        ftfCodigo.setEditable(false);
        tfNome.setText(militar.getNome());
        tfNome.setEditable(false);
        ftfCpf.setText(militar.getCpf());
        ftfRg.setText(militar.getRg());
        ftfIdade.setText(String.valueOf(militar.getIdade()));
        ftfIdade.setEnabled(false);
        cbEstado.setSelectedItem(militar.getEstado());
        cbEstado.setEditable(false);
        ftfNascimento.setText(militar.getNascimento());
        ftfNascimento.setEditable(false);
        rbMasculino.setSelected("Masculino".equals(militar.getSexo()));
        rbMasculino.setEnabled(false);
        rbFeminino.setSelected(militar.getSexo() == "Feminino");
        rbFeminino.setEnabled(true);
        rbSoldado.setSelected(militar.getPatente()== "Soldado");
        rbSoldado.setEnabled(false);
        rbTenente.setSelected(militar.getPatente()== "Tenente");
        rbTenente.setEnabled(false);
        rbCapitao.setSelected(militar.getPatente()== "Capitao");
        rbCapitao.setEnabled(false);
        rbMajor.setSelected(militar.getPatente()== "Major");
        rbMajor.setEnabled(false);
        rbCoronel.setSelected(militar.getPatente()== "Coronel");
        rbCoronel.setEnabled(false);
        rbMarechal.setSelected(militar.getPatente()== "Marechal");
        rbMarechal.setEnabled(false);
        rbComando.setSelected(militar.getPatente()== "Comandante");
        rbComando.setEnabled(false);
        
           
    }//GEN-LAST:event_BtBuscarSoldadoActionPerformed

    private void jbCadastrarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarTarefaActionPerformed

        militar.setDescascar(chkDescascarBatatas.isSelected());
        militar.setLimparBanheiro(chkLimparBanheiro.isSelected());
        militar.setLimparCozinha(chkLimparCozinha.isSelected());
        militar.setCozinharArmoco(chkCozinharAlmoco.isSelected());
        militar.setCozinharJanta(chkCozinharJanta.isSelected());
        militar.setAlimentarCavalos(chkAlimentarCavalos.isSelected());
        militar.setLimparEstabulos(chkLimparEstabulos.isSelected());
        militar.setRecarregarArmamento(chkRecarregar.isSelected());
        militar.setTrocarEncanamento(chkTrocarEncanamento.isSelected());
        militar.setLevantarBandeira(chkLevantarBandeira.isSelected());
        //limpar campos e inabilitar
        rbSoldado.setEnabled(true);
        rbTenente.setEnabled(true);
        rbCapitao.setEnabled(true);
        rbMajor.setEnabled(true);
        rbCoronel.setEnabled(true);
        rbMarechal.setEnabled(true);
        chkDescascarBatatas.setEnabled(false);
        chkLimparBanheiro.setEnabled(false);
        chkLimparCozinha.setEnabled(false);
        chkLimparEstabulos.setEnabled(false);
        chkRecarregar.setEnabled(false);
        chkAlimentarCavalos.setEnabled(false);
        chkCozinharAlmoco.setEnabled(false);
        chkCozinharJanta.setEnabled(false);
        chkTrocarEncanamento.setEnabled(false);
        chkLevantarBandeira.setEnabled(false);
        insererClienteArray(militar);
        limparCamposFrame();

    }//GEN-LAST:event_jbCadastrarTarefaActionPerformed

    private void btListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarActionPerformed
      
        listarTodosClientesArray();

    }//GEN-LAST:event_btListarActionPerformed

    private void rbMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMasculinoActionPerformed

    private void rbComandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbComandoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rbComandoActionPerformed

    private void jbTarefaFeitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTarefaFeitaActionPerformed
       
        excluirSoldadoArray(tfNome.getText());
        militar = null;
        limparCamposFrame();
        
        
    }//GEN-LAST:event_jbTarefaFeitaActionPerformed
     private void excluirSoldadoArray(String nome){
        Militar soldado = null;
        for(int i=0;i<milit.size();i++){
            if(nome.equals(milit.get(i).getNome())){
                System.out.println("Soldado: "+milit.get(i).getNome());
                milit.get(i).setLimparCozinha(false);
                milit.get(i).setAlimentarCavalos(false);
                /*
                milit.remove(chkDescascarBatatas);
                milit.remove(chkLimparBanheiro);
                milit.remove(chkLimparCozinha);
                milit.remove(chkLimparEstabulos);
                milit.remove(chkRecarregar);
                milit.remove(chkCozinharAlmoco);
                milit.remove(chkCozinharJanta);
                milit.remove(chkTrocarEncanamento);
                milit.remove(chkLevantarBandeira);
                */
                
                
                
                JOptionPane.showMessageDialog(null,"tarefa excluido com sucesso!");
            }
        }
        if(soldado == null){
                JOptionPane.showMessageDialog(null,"Cliente não encontrado.");
        }
    }
    
   

//limpa os campos de  cadastro 
    
    public void limparCamposFrame(){
        ftfCodigo.setText("");  
        tfNome.setText("");
        ftfCpf.setText("");
        ftfRg.setText("");
        ftfNascimento.setText("");
        ftfIdade.setText("");
        cbEstado.setSelectedIndex(-1);
        buttonGroup2.clearSelection();
        buttonGroup1.clearSelection();
        chkDescascarBatatas.setSelected(false);
                chkLimparBanheiro.setSelected(false);
                chkLimparCozinha.setSelected(false);
                chkLimparEstabulos.setSelected(false);
                chkRecarregar.setSelected(false);
                chkAlimentarCavalos.setSelected(false);
                chkCozinharAlmoco.setSelected(false);
                chkCozinharJanta.setSelected(false);
                chkTrocarEncanamento.setSelected(false);
                chkLevantarBandeira.setSelected(false);
                
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tarefas_Militares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tarefas_Militares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tarefas_Militares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tarefas_Militares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tarefas_Militares().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBuscarSoldado;
    private javax.swing.JPanel JpDadosSoldado;
    private javax.swing.JLabel LbCodigo;
    private javax.swing.JLabel LbCpf;
    private javax.swing.JLabel LbEstado;
    private javax.swing.JLabel LbIdade;
    private javax.swing.JLabel LbNascimento;
    private javax.swing.JLabel LbNome;
    private javax.swing.JLabel LbRg;
    private javax.swing.JLabel LbSexo;
    private javax.swing.JButton btCadastrarSoldado;
    private javax.swing.JButton btDeletarSoldado;
    private javax.swing.JToggleButton btListar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JCheckBox chkAlimentarCavalos;
    private javax.swing.JCheckBox chkCozinharAlmoco;
    private javax.swing.JCheckBox chkCozinharJanta;
    private javax.swing.JCheckBox chkDescascarBatatas;
    private javax.swing.JCheckBox chkLevantarBandeira;
    private javax.swing.JCheckBox chkLimparBanheiro;
    private javax.swing.JCheckBox chkLimparCozinha;
    private javax.swing.JCheckBox chkLimparEstabulos;
    private javax.swing.JCheckBox chkRecarregar;
    private javax.swing.JCheckBox chkTrocarEncanamento;
    private javax.swing.JFormattedTextField ftfCodigo;
    private javax.swing.JFormattedTextField ftfCpf;
    private javax.swing.JFormattedTextField ftfIdade;
    private javax.swing.JFormattedTextField ftfNascimento;
    private javax.swing.JFormattedTextField ftfRg;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JButton jbCadastrarTarefa;
    private javax.swing.JButton jbTarefaFeita;
    private javax.swing.JRadioButton rbCapitao;
    private javax.swing.JRadioButton rbComando;
    private javax.swing.JRadioButton rbCoronel;
    private javax.swing.JRadioButton rbFeminino;
    private javax.swing.JRadioButton rbMajor;
    private javax.swing.JRadioButton rbMarechal;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JRadioButton rbSoldado;
    private javax.swing.JRadioButton rbTenente;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
